language: node_js
node_js:
- '6.9'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
deploy:
  provider: heroku
  api_key:
    secure:CaFYT5MRRlE+JetYjQH6FpMTG0damZipKZlXDHU1OCpkfxj80qDJdB6RSQQ8Jn3KjesfS+t9gJY3Q4giqnH0us+kkexjLbmPHSPEKJHdcgl99BGOoXvzi8l7HMIjPWVwFEtKDwhaOF7uWyfhFuSCsqKoi6f/tngdK2qzTA+rJ0uhGKHjZdmuwxsB3qfyMVrm3MZExT/VS97bY0vfxijq/S1JGkbKLp29fZe+CoxIMHlYCleR3To8kGNrABNxgRMehES7uGKWj3cTQcDdWerQeqHha+Qm9YbZp/e2m8yaJoqoBcNMGjMreli3VzL6bLgbhss0E8NkvsafUKnkb5IjtHyhKb02YpFVuowdRosKb53ZQ/i7oM6H1ILnIGy+Wd3G6IjJ8sYTtK9kxh0XUtsYRCxIVa3syQFAZzgdooqrwxKhCW6UCBB20OzvRLQ5QDUjvJ9f4oICgsmlzqRmAxWTZVmZnEUj6miPHW4nhSDTtjhcHIRztS31iw4fHlYoDPKIwbdsplWE2j6y3WktMgRebKyuaFze/R6P+NSIEi2BYuJbNfYlCYO9HQqD78fIVUwT67gXZJIGD6k7rGebN4bZlZh0PIOnCrUYRzYE27Kcw954kCnJD+zOfh6BIre31JXX21pgHQFc//C7gq4otx/qb7jSNmHlACi6mCBUSw/u7ro=
